from alembic import op
import sqlalchemy as sa
revision="0001_foundation"
 down_revision=None
 branch_labels=None
 depends_on=None
def upgrade():
    op.create_table("processing_jobs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("status",sa.String(32),nullable=False),sa.Column("telegram_file_id",sa.String(255),nullable=False),sa.Column("original_filename",sa.String(255)),sa.Column("content_type",sa.String(128)),sa.Column("file_size_bytes",sa.Integer(),nullable=False),sa.Column("submitted_by",sa.Integer(),nullable=False),sa.Column("mode",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("artifacts",sa.Column("artifact_id",sa.String(36),primary_key=True),sa.Column("job_id",sa.String(36),sa.ForeignKey("processing_jobs.id"),nullable=False),sa.Column("type",sa.String(64),nullable=False),sa.Column("storage_path",sa.Text(),nullable=False),sa.Column("mime_type",sa.String(128),nullable=False),sa.Column("size_bytes",sa.Integer(),nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("metadata",sa.JSON(),nullable=False))
    op.create_table("job_steps",sa.Column("id",sa.String(36),primary_key=True),sa.Column("job_id",sa.String(36),sa.ForeignKey("processing_jobs.id"),nullable=False),sa.Column("name",sa.String(128),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("duration_ms",sa.Integer()),sa.Column("retry_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("error",sa.Text()))
    op.create_table("design_specs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("job_id",sa.String(36),sa.ForeignKey("processing_jobs.id"),nullable=False),sa.Column("schema_version",sa.Integer(),nullable=False),sa.Column("document",sa.JSON(),nullable=False))
    op.create_table("processing_settings",sa.Column("id",sa.String(36),primary_key=True),sa.Column("job_id",sa.String(36),nullable=False),sa.Column("schema_version",sa.Integer(),nullable=False),sa.Column("document",sa.JSON(),nullable=False))
    op.create_table("ai_executions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("job_id",sa.String(36),nullable=False),sa.Column("provider",sa.String(64),nullable=False),sa.Column("model_id",sa.String(128)),sa.Column("duration_ms",sa.Integer()),sa.Column("status",sa.String(32),nullable=False),sa.Column("metadata",sa.JSON(),nullable=False))
    op.create_table("models",sa.Column("model_id",sa.String(128),primary_key=True),sa.Column("version",sa.String(64),nullable=False),sa.Column("exact_source",sa.Text()),sa.Column("exact_weight_source",sa.Text()),sa.Column("weight_sha256",sa.String(64)),sa.Column("code_license",sa.String(128),nullable=False),sa.Column("weights_license",sa.String(128),nullable=False),sa.Column("commercial_allowed",sa.Boolean(),nullable=False),sa.Column("redistribution_allowed",sa.Boolean(),nullable=False),sa.Column("attribution_required",sa.Boolean(),nullable=False),sa.Column("gpu_required",sa.Boolean(),nullable=False),sa.Column("minimum_vram_mb",sa.Integer()),sa.Column("recommended_vram_mb",sa.Integer()),sa.Column("backend",sa.String(64)),sa.Column("precision",sa.String(32)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_source",sa.Text()))
    op.create_table("workflows",sa.Column("workflow_id",sa.String(128),primary_key=True),sa.Column("version",sa.String(32),nullable=False),sa.Column("definition",sa.JSON(),nullable=False))
def downgrade():
    for t in ("workflows","models","ai_executions","processing_settings","design_specs","job_steps","artifacts","processing_jobs"):
        op.drop_table(t)